### ISSUE TITLE
Initialize AwsAuthenticator with an AWS SDK Session?

### ISSUE THREAD

**Issue by zxia-wish** [aws/aws-sigv4-auth-cassandra-gocql-driver-plugin#4]
Hello team,

I hope you are doing well. I wonder if it is possible to initialize an AwsAuthenticator object with a AWS SDK Session, like the [Python SigV4 plugin](https://github.com/aws/aws-sigv4-auth-cassandra-python-driver-plugin). In some cases, permission is granted by roles/policies in a k8s cluster and therefore impossible (or very hard) to acquire the respective keys.

Thanks!

**Comment by bhouse99** [comment]
Thanks so much for the suggestion!   We'll take a look at this and consider it for our roadmap.

**Comment by wizardishungry** [comment]
This also affects users using the cli/sdk locally with SSO. I think I have a workaround for now, but I'd like to see this [use the proper sdk instead of reimplementing v4](https://docs.aws.amazon.com/sdk-for-go/api/aws/signer/v4/):
```go
var auth sigv4.AwsAuthenticator = sigv4.NewAwsAuthenticator()
awsSess, _ := session.NewSession()
cred, _ := awsSess.Config.Credentials.Get()
auth.AccessKeyId = cred.AccessKeyID
auth.SecretAccessKey = cred.SecretAccessKey
auth.Region = *awsSess.Config.Region
auth.SessionToken = cred.SessionToken
```
cc @zxia-wish

**Comment by rohangupta** [comment]
This change has been implemented.
