### ISSUE TITLE
Support for refreshable credentials

### ISSUE THREAD

**Issue by pergardebrink** [aws/aws-sigv4-auth-cassandra-gocql-driver-plugin#8]
We have a use-case where we need to do cross-account access to AWS Keyspaces.

Since this need to be done through an IAM Role in the target account (as detailed here: https://docs.aws.amazon.com/keyspaces/latest/devguide/security-iam.html), we have to use AssumeRole, meaning that the credentials we get from the AssumeRole call needs to be refreshed at regular intervals when it expires. 

I see that there's already a PR (https://github.com/aws/aws-sigv4-auth-cassandra-gocql-driver-plugin/pull/7) open that seems like it would solve our use-case. Is there anything that blocks it from being merged that we can help out with?

**Comment by rohangupta** [comment]
The PR has been merged now.
